# Generated by Django 2.2.4 on 2019-08-12 00:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('theater_operas', '0002_auto_20190811_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='mention',
            name='mention_number',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
