# Generated by Django 2.2.4 on 2019-08-12 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theater_operas', '0003_mention_mention_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mention',
            name='mention_number',
        ),
    ]
