# Generated by Django 2.2.4 on 2019-08-12 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater_operas', '0004_remove_mention_mention_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='mention',
            name='mention_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
