# Generated by Django 2.2.4 on 2019-08-12 09:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('theater_operas', '0006_remove_mention_mention_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='mention',
            name='mention_number',
            field=models.FloatField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
