# Generated by Django 2.2.4 on 2019-08-12 09:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('theater_operas', '0007_mention_mention_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mention',
            name='mention_number',
        ),
        migrations.AddField(
            model_name='mention',
            name='mention_link',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
