# Generated by Django 2.2.4 on 2019-08-12 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theater_operas', '0008_auto_20190812_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mention',
            old_name='image',
            new_name='cover',
        ),
        migrations.RemoveField(
            model_name='mention',
            name='mention_link',
        ),
    ]
